version: '3'
services:
 backend:
  build: ./sunflower
  command: python manage.py runserver 0.0.0.0:8000
  entrypoint: ["./entrypoint.sh"]
  volumes:
   - ./sunflower:/code
  ports:
   - "${WEB_PORT}:8000"
  env_file:
   - '.env'
  depends_on:
   - db
 db:
  image: postgres:15.3
  env_file:
   - '.env'
  ports:
   - "${DB_PORT}:5432"
  volumes:
   - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  backend:
