version: '3'
services:
  backend:
    build: ./sunflower
    command: ["invoke", "run-api", "--port", "${BE_PORT}", "--db-port", "${DB_PORT}"]
    restart: on-failure
    volumes:
      - ./sunflower:/code
      - staticfiles:/code/staticfiles/
      - media:/code/media/
    ports:
      - "${BE_PORT}:8000"
    env_file:
      - '.env'
    depends_on:
      - db
  db:
    image: postgres:15.3
    env_file:
    - '.env'
    ports:
    - "${DB_PORT}:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
  nginx:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    volumes:
      - staticfiles:/staticfiles
      - media:/media
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - backend
volumes:
  postgres-data:
  staticfiles:
  media:
