version: '3'
services:
  backend:
    build: ./sunflower
    command: ["invoke", "run-api", "--port", "${BE_PORT}", "--db-port", "${DB_PORT}"]
    restart: on-failure
    volumes:
      - ./sunflower:/code
    ports:
      - "${BE_PORT}:8000"
    env_file:
      - '.env'
    depends_on:
      - db
  frontend:
    build:
      context: ./sunflower_fe
    volumes:
      - ./sunflower_fe:/code_fe
    ports:
      - "${WEB_PORT}:3000"
    command: npm start
    env_file:
      - '.env'
    depends_on:
      - backend
  db:
    image: postgres:15.3
    env_file:
    - '.env'
    ports:
    - "${DB_PORT}:5432"
    volumes:
    - /var/lib/postgresql/data
