# Generated by Django 4.2.1 on 2023-07-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "size",
                    models.CharField(
                        choices=[("s", "Small"), ("m", "Medium"), ("l", "Large")],
                        max_length=3,
                        verbose_name="Size",
                    ),
                ),
            ],
        ),
    ]
