# Generated by Django 4.2.1 on 2023-07-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("order", "name"),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[("s", "Small"), ("m", "Medium"), ("l", "Large")],
                db_index=True,
                max_length=3,
                verbose_name="Size",
            ),
        ),
    ]
