# Generated by Django 4.1.7 on 2023-10-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_product_options_product_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="picture",
            field=models.ImageField(
                null=True, upload_to="images/stickers/", verbose_name="Image"
            ),
        ),
    ]
